//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_calendar.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendar
    {
        public Calendar()
        {
            this.CalendarEventsCollection = new HashSet<CalendarEvent>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Text { get; set; }
        public Nullable<int> CalendarColor { get; set; }
        public Nullable<int> CalendarEvents { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> ShowedDateTime { get; set; }
    
        public virtual ICollection<CalendarEvent> CalendarEventsCollection { get; set; }
    }
}
