//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationRepository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.guests = new HashSet<Guest>();
            this.notifications = new HashSet<Notification>();
            this.repeatables = new HashSet<Repeatable>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string text { get; set; }
        public string place { get; set; }
        public System.DateTime time_begin { get; set; }
        public Nullable<System.DateTime> time_end { get; set; }
        public string visibility { get; set; }
        public Nullable<bool> all_day { get; set; }
        public Nullable<int> calendar_id { get; set; }
    
        public virtual Calendar calendar { get; set; }
        public virtual ICollection<Guest> guests { get; set; }
        public virtual ICollection<Notification> notifications { get; set; }
        public virtual ICollection<Repeatable> repeatables { get; set; }
    }
}
