//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_calendar.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationType
    {
        public NotificationType()
        {
            this.Calendars = new HashSet<Calendar>();
            this.Notifications = new HashSet<Notification>();
        }
    
        public int Id { get; set; }
        public Nullable<int> RepetitionCount { get; set; }
        public Nullable<int> Interval { get; set; }
        public Nullable<int> TimeBefore { get; set; }
        public string KindOfNotification { get; set; }
    
        public virtual ICollection<Calendar> Calendars { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
    }
}
