//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationRepository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationType
    {
        public NotificationType()
        {
            this.notifications = new HashSet<Notification>();
        }
    
        public int id { get; set; }
        public Nullable<int> repetition_count { get; set; }
        public Nullable<int> interval { get; set; }
        public Nullable<int> time_before { get; set; }
        public string kind_of_notification { get; set; }
    
        public virtual ICollection<Notification> notifications { get; set; }
    }
}
