//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_calendar.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repeatable
    {
        public int Id { get; set; }
        public string Period { get; set; }
        public Nullable<int> RepeatCount { get; set; }
        public Nullable<int> EventId { get; set; }
        public string DaysOfWeek { get; set; }
        public Nullable<System.TimeSpan> TimeOfDay { get; set; }
        public Nullable<System.DateTime> DayOfYear { get; set; }
        public Nullable<int> DayOfMonth { get; set; }
    
        public virtual CalendarEvent CalendarEvent { get; set; }
    }
}
