//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationRepository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Settings
    {
        public Settings()
        {
            this.users = new HashSet<User>();
        }
    
        public int id { get; set; }
        public Nullable<byte> timezone { get; set; }
        public string weekstart { get; set; }
        public string default_view { get; set; }
    
        public virtual ICollection<User> users { get; set; }
    }
}
