//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationRepository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSetting
    {
        public UserSetting()
        {
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public Nullable<byte> TimeZone { get; set; }
        public string WeekStart { get; set; }
        public string DefaultView { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
