//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationRepository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.CalendarsCollection = new HashSet<Calendar>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string PasswordHash { get; set; }
        public string Email { get; set; }
        public Nullable<int> Calendars { get; set; }
        public Nullable<int> UserSettingsId { get; set; }
        public string Role { get; set; }
        public Nullable<bool> EmailConfirmed { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public Nullable<bool> LockoutEnabled { get; set; }
        public Nullable<int> AccessFailedCount { get; set; }
    
        public virtual ICollection<Calendar> CalendarsCollection { get; set; }
        public virtual UserSetting UserSetting { get; set; }
    }
}
