//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationRepository.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class web_calendarEntities : DbContext
    {
        public web_calendarEntities()
            : base("name=web_calendarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Calendar> calendars { get; set; }
        public virtual DbSet<Event> events { get; set; }
        public virtual DbSet<Guest> guests { get; set; }
        public virtual DbSet<Notification> notifications { get; set; }
        public virtual DbSet<NotificationType> notification_type { get; set; }
        public virtual DbSet<Repeatable> repeatables { get; set; }
        public virtual DbSet<Settings> settings { get; set; }
        public virtual DbSet<User> users { get; set; }  
    }
}
